var message = "Vamos la buscar as esferas do Dragão.";
console.log(message);
var episode = 4;
console.log("Episodio numero: " + episode);
episode = episode + 1;
console.log("próximo Episodio: " + episode);
//episode = '3';
episode = episode + 1;
console.log("próximo Episodio com Erro: " + episode);
var favoriteDroid; // estamos implicitamente usando o tipo any; Pode ter qualquer valor com o tipo Any;
favoriteDroid = 'BB-8';
favoriteDroid = 10;
var favoriteString; // correto é s minusculo, string não String;
favoriteString = "ola";
console.log("My favorite Droid: " + favoriteString);
